// @flow

export const APP_ERROR_CODE_UPDATE = "APP_ERROR_CODE_UPDATE";
export const APP_NOTIFICATIONS_ADD = "APP_NOTIFICATIONS_ADD";
export const APP_NOTIFICATIONS_REMOVE = "APP_NOTIFICATIONS_REMOVE";
export const REGISTRATION_FORM_UPDATE = "REGISTRATION_FORM_UPDATE";
export const USER_IDENTITY_UPDATE = "USER_IDENTITY_UPDATE";
export const USER_TOKEN_UPDATE = "USER_TOKEN_UPDATE";
export const LOGIN_FORM_UPDATE = "LOGIN_FORM_UPDATE";
export const USER_DETAILS_UPDATE = "USER_DETAILS_UPDATE";
export default {
  APP_ERROR_CODE_UPDATE,
  APP_NOTIFICATIONS_ADD,
  APP_NOTIFICATIONS_REMOVE,
  USER_IDENTITY_UPDATE,
  USER_TOKEN_UPDATE,
  USER_DETAILS_UPDATE,
};
