# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    #  send all emails to a specific address
    #delivery_addresses: ['me@example.com']
    transport: smtp
    host: smtp.gmail.com
    port: 587
    encryption: tls
    username: blockchaindev0125@gmail.com
    password: $Wanshai1997$